server:
  port: 80

spring:
  application:
    name: customer-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #集群
      #http://localhost:7002/eureka