server:
  port: 9002

spring:
  application:
    name: cloud-nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: 127.0.0.1:8848
        server-addr: 172.16.10.10:1111  # nginx的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'