server:
  port: 3344


spring:
  application:
    name: cloud-config-center  #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:weixiaouser/springcloud-config.git  #github上git仓库名字
          #搜索目录
          search-paths:
            - springcloud-config
          #读取分支
          label: master



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka

#RabbitMQ的配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'