server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}